Revert "Move rendered CRD files dir to /api/crd and link"
This reverts commit 47d5e81f6d10b0d9144c43deae71f5769d468078.

Due to error in `make bundle` where one issues is that kustomize
autodetect fails on symlinked directory.

/home/runner/work/keystone-operator/keystone-operator/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../default': '/home/runner/work/keystone-operator/keystone-operator/config/default' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/home/runner/work/keystone-operator/keystone-operator/config/default': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../crd': '/home/runner/work/keystone-operator/keystone-operator/config/crd' must resolve to a file\"\n\t* accumulateDirector error: \"recursed accumulation of path '/home/runner/work/keystone-operator/keystone-operator/config/crd': accumulating resources: 2 errors occurred:\\n\\t* accumulateFile error: \\\"accumulating resources from 'bases/keystone.openstack.org_keystoneapis.yaml': security; file '/home/runner/work/keystone-operator/keystone-operator/config/crd/bases/keystone.openstack.org_keystoneapis.yaml' is not in or below '/home/runner/work/keystone-operator/keystone-operator/config/crd'\\\"\\n\\t* loader.New error: \\\"error loading bases/keystone.openstack.org_keystoneapis.yaml with git: url lacks host: bases/keystone.openstack.org_keystoneapis.yaml, dir: got file 'keystone.openstack.org_keystoneapis.yaml', but '/home/runner/work/keystone-operator/keystone-operator/config/crd/bases/keystone.openstack.org_keystoneapis.yaml' must be a directory to be a root, get: invalid source string: bases/keystone.openstack.org_keystoneapis.yaml\\\"\\n\\n\"\n\n"